CoroutineScope job should be canceled before destory
google/filament pull request #3050
Opened 2020-09-08 06:52 UTC by daichen

tombstone happens if run destory while loadModelGltfAsync in ModelViewer.kt

To Reproduce
1.loadModelGltfAsync
2.detach from the winodw quickly
3.tombstone ..

2020-09-08 15:28 UTC, romainguy requested changes
Thank you for your contribution! I only have a couple of comments

2020-09-08 15:28 UTC, romainguy commented on android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
> +                fetchResJob?.cancel()
destroyModel() is called below which will call cancel on the job, is it necessary to cancel here as well?

2020-09-08 15:28 UTC, romainguy commented on android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
> +    private var fetchResJob: Job? = null
Please rename to `fetchResourcesJob`

2020-09-09 03:02 UTC, daichen commented
sorry, I'm not familiar with git hub, I will close this request and create a new request

2020-09-09 03:02 UTC, closed without merging