fix memory leak issue in reource loader
google/filament pull request #3063
Opened 2020-09-10 06:38 UTC by daichen

shoule release texels before destory or reload

To Reproduce

1. start android sample-gltf-viewer
2. keep on double tabing the activity to reload the model
3. monitor the memory useage

2020-09-10 15:55 UTC, romainguy requested changes
Thanks for the fix, please see comments below.

2020-09-10 15:55 UTC, romainguy commented on libs/gltfio/src/ResourceLoader.cpp
> +    releaseTexels();
This needs to be done after waiting for the decoder job to finish below.

2020-09-10 17:21 UTC, prideout commented
Search this file for `PixelBufferDescriptor` and note that the `texels` pointer should be freed when the PixelBufferDescriptor callback is triggered.  If you're seeing a leak, can you determine why the PixelBufferDescriptor callback isn't being triggered?

2020-09-10 19:34 UTC, pixelflinger commented
A quick inspection of the code doesn't explain how the callback could not be called after `setImage` has been called. So we need to investigate this more.

2020-09-10 20:21 UTC, pixelflinger commented
okay more details about this -- the leak happens only when triggering a reload (double-tap) while a reload is already happening.  My guess is that there is a code path where malloc() is called and `setImage` is not.

2020-09-11 02:12 UTC, daichen commented
It is because com.google.android.filament.utils.ModelViewer load the resource use asyncBeginLoad, it will not call  uploadPendingTextures in createTextures.
After ModelViewer call asyncUpdateLoad in render(), it will send image to gpu and set callback free the memory

2020-09-16 06:26 UTC, daichen commented
please reivew https://github.com/google/filament/pull/3063/commits/fa1bbe5c36e428be834f4d3aff71242c2ed4c55b

2020-09-21 21:25 UTC, prideout commented
I am back from vacation and will take a look at this soon.

2020-09-22 21:35 UTC, prideout commented
Thanks for bringing this to our attention!  I have an alternative fix up (#3109) that handles this in addition to a couple other missing cancellation features (e.g. an assert in DependencyGraph, zombie decoder threads)

2020-09-22 21:35 UTC, closed without merging