Add support for transparent shadows
google/filament pull request #3298
Opened 2020-11-18 02:14 UTC by romainguy

This solution uses an 8x8 Bayer matrix. We could find a better
noise. We also need better filtering of the shadow maps. A PCF
is barely enough and VSM fails without blurring.

<img width="1644" alt="Screen Shot 2020-11-17 at 6 10 04 PM" src="https://user-images.githubusercontent.com/869684/99474007-a894e080-2900-11eb-8264-3c05e9f5a5af.png">

2020-11-27 14:24 UTC, israelillan approved these changes

2020-11-27 14:26 UTC, FabianRueckert approved these changes

2021-04-01 21:43 UTC, romainguy commented
Note: I'll revisit this PR once we provide support for blurred VSMs (CC @bejado).

2021-07-08 17:22 UTC, pixelflinger approved these changes

2021-07-08 17:23 UTC, pixelflinger requested changes
Add an entry in the release notes?

2021-07-08 17:31 UTC, merged