CString can construct from a string_view
google/filament pull request #3677
Opened 2021-03-22 16:36 UTC by AdrianAtGoogle

(string_views lack a null terminator)

2021-03-22 16:37 UTC, romainguy reviewed
LGTM, but I'll let @pixelflinger approve

2021-03-22 17:06 UTC, pixelflinger approved these changes
wow. good one.

2021-03-22 20:43 UTC, pixelflinger commented
strangely it looks like this is breaking stuff. I'm going to have a look next.

2021-03-22 20:52 UTC, pixelflinger requested changes

2021-03-22 20:52 UTC, pixelflinger commented on libs/utils/src/CString.cpp
> +        mCStr[length + 1] = '\0';
```suggestion
        mCStr[length] = '\0';
```

2021-03-23 07:46 UTC, merged

2021-03-23 15:38 UTC, AdrianAtGoogle commented
lol thanks for the off-by-1 fix :)