New experimental tone mapper
google/filament pull request #3850
Opened 2021-04-24 06:17 UTC by romainguy

The new tone mapper proposed in this change replaces Uchimura (see
below) and is composed of two distinct algorithms:

- The first is the customizable compression curve from Timothy Lotte
  (from GDC 2015). The curve's default parameters were chosen to
  match the overall appearance (contrast) of the ACES curves used
  as our current default tone mapper. This was done to provide a
  good migration path to making this new solution the default in
  a future version of Filament.
  The compression curve can be customized via its contrast, shoulder,
  input middle gray, output middle gray, and maximum "HDR value"
  (scene referred).
  It is important to note that the compression is only applied to
  the luminance of the input scene referred value.

- The second is a novel approach by Troy Sobotka called Exposure
  Value Invariant Luminance Scaling (or EVILS). This solution works
  on the largest chromatic channel of the input value as opposed
  to mapping all RGB channels as we do in our other tone mappers.
  The algorithm effectively scales all channel by a ratio that
  depends on both the compressed luminance from the first stage
  and the luminance of input value normalized by the largest
  channel.

This new solution offers important benefits as it manages to
preserve chromaticity for high input values. It is also designed
to provide a desirable rolloff to white on overexposure. This
means that even without gamut mapping, this solution avoids many
hue skews (red to orange, blue to purple, etc.). The results
provided by this solution are much more natural and make using
other color grading tools much easier.

We replace Uchimura in this change — technically an API
breakage — because Uchimura suffers from heavy hue skews and
does not offer any benefits over this new solution. Our other tone
mappers remain useful for backward compatibility (`Filmic`) or
for validation with other tools/engines (`ACES`, `Reinhard`).

Here are various comparisons with `ACES (Legacy)`, our default
tone mapper.

Bistro scene with ACES, notice the skew on the red awning:
<img width="1390" alt="Screen Shot 2021-04-23 at 7 51 31 PM" src="https://user-images.githubusercontent.com/869684/115949316-2a2d0380-a489-11eb-9796-2dcce6df1bd6.png">

With EVILS, the skew disappears in favor of a rolloff to white:
<img width="1390" alt="Screen Shot 2021-04-23 at 7 51 26 PM" src="https://user-images.githubusercontent.com/869684/115949354-6b251800-a489-11eb-9b11-625acb6c1bea.png">

Primaries test scene with ACES, notice how the blue sphere skews
to purple, the red sphere to orange, and the green plane to yellow:
<img width="1136" alt="Screen Shot 2021-04-23 at 7 52 04 PM" src="https://user-images.githubusercontent.com/869684/115949361-7bd58e00-a489-11eb-9eee-da63fddbe1e5.png">

With EVILS, chromaticity is properly retained with a rolloff to white
on the most intense areas directly illuminated by the ~150,000 lux
directional light:
<img width="1136" alt="Screen Shot 2021-04-23 at 7 52 01 PM" src="https://user-images.githubusercontent.com/869684/115949371-94de3f00-a489-11eb-9ca0-b6380b5aa708.png">

Blue light saber with ACES, notice the hue skew again:
<img width="1510" alt="Screen Shot 2021-04-23 at 8 37 57 PM" src="https://user-images.githubusercontent.com/869684/115949403-cce58200-a489-11eb-8793-b51738afea21.png">

With EVIL, the skew is gone:
<img width="1510" alt="Screen Shot 2021-04-23 at 8 37 48 PM" src="https://user-images.githubusercontent.com/869684/115949410-da027100-a489-11eb-8ee8-2b51b60efec9.png">

Red light saber with ACES, notice how the core skews to orange:
<img width="1510" alt="Screen Shot 2021-04-23 at 8 39 06 PM" src="https://user-images.githubusercontent.com/869684/115949431-f4d4e580-a489-11eb-8d09-78b99237fd8d.png">

With EVILS, the skew is gone:
<img width="1510" alt="Screen Shot 2021-04-23 at 8 39 09 PM" src="https://user-images.githubusercontent.com/869684/115949434-fe5e4d80-a489-11eb-811a-fca9ab3ccb19.png">

2021-04-24 06:23 UTC, pixelflinger requested changes

2021-04-24 06:23 UTC, pixelflinger commented on filament/src/ColorGrading.cpp
> +                    uint32_t b = uint32_t(floor(v.z * 1023.0f + 0.5f));
usually we use `std::floor`

2021-04-24 06:23 UTC, pixelflinger commented on filament/src/ToneMapping.cpp
> +#include <iostream>
we shouldn't need `iostream`

2021-04-24 06:23 UTC, pixelflinger commented on filament/src/ToneMapping.cpp
> +    float mc = pow(midGreyIn, contrast);
`std::pow` everywhere

2021-04-24 06:28 UTC, romainguy commented on filament/src/ColorGrading.cpp
> +                    uint32_t b = uint32_t(floor(v.z * 1023.0f + 0.5f));
Done

2021-04-24 06:29 UTC, romainguy commented on filament/src/ToneMapping.cpp
> +#include <iostream>
Done

2021-04-24 06:29 UTC, romainguy commented on filament/src/ToneMapping.cpp
> +    float mc = pow(midGreyIn, contrast);
Done

2021-04-24 06:33 UTC, pixelflinger approved these changes

2021-04-26 15:35 UTC, prideout approved these changes

2021-04-26 19:08 UTC, bejado approved these changes

2021-04-27 01:09 UTC, merged