Support a maximum of 8 render buffers (from 4)
google/filament pull request #3882
Opened 2021-05-03 18:10 UTC by pixelflinger

We chose 8 renderbuffer because it seems to be commonly supported
on mobile gpu and is more than 6 which is needed for generating
cubemaps. 4 was the minimum guaranteed by ES3.0.

The main changes here are:
- TargetBufferFlags is now a uint32_t instead of uint8_t
- The number of render buffer supported by filament and supported by
  the hardware can now be different. Applications/users now must
  query this value if more than 4 is needed.
- added a backend query (used gl terminology)

This is a redo of a previous attempt. There was an issue in the GL
backend that caused MRT to fail on some devices.

2021-05-03 18:31 UTC, romainguy approved these changes

2021-05-03 18:51 UTC, bejado approved these changes

2021-05-03 20:07 UTC, prideout requested changes
Mathias can you also update `VulkanDriver::blit`?  There is a sequence of `if` statements in there that should probably be changed into a loop.

2021-05-04 16:39 UTC, prideout approved these changes
Thanks!

2021-05-04 17:53 UTC, merged