ShadowMapManager: fix MSAN use-of-uninitialized-value.
google/filament pull request #4247
Opened 2021-07-06 18:54 UTC by prideout

The operator!= in std::array compares SPLIT_COUNT elements, which
is potentially greater than cascadeCount, which was the number of
initialized elements in splitPercentages.

2021-07-06 21:41 UTC, romainguy approved these changes

2021-07-06 21:41 UTC, romainguy commented
This reminds me why I don't like `std::array` :)

2021-07-07 00:04 UTC, pixelflinger requested changes

2021-07-07 00:04 UTC, pixelflinger commented on filament/src/ShadowMapManager.cpp
>      splitPercentages[0] = 0.0f;
This line is not needed anymore.

2021-07-07 14:49 UTC, prideout commented on filament/src/ShadowMapManager.cpp
>      splitPercentages[0] = 0.0f;
Good catch.

2021-07-07 14:51 UTC, merged