Add Java / WebGL bindings for screen-space reflections
google/filament pull request #5054
Opened 2022-01-14 20:15 UTC by bejado

2022-01-14 20:26 UTC, prideout commented
🍾  Sweet I will take a look!

2022-01-14 21:37 UTC, pixelflinger approved these changes

2022-01-14 21:48 UTC, prideout commented on libs/viewer/src/Settings.cpp
> +               << "\"stride\": " << in.stride << ",\n"
I think this has the dreaded trailing comma of death 😱

2022-01-14 21:50 UTC, prideout requested changes
Trailing comma, otherwise looks great.

2022-01-19 20:50 UTC, merged

2025-12-22 17:39 UTC, lucasleandro1805 commented
@bejado please add reflection bindings in MaterialBuilder (Java/WEBGL).
We cannot change from default to screen-space reflection mode in MaterialBuilder using java.