allow a scene to have both transmission and reflection
google/filament pull request #5069
Opened 2022-01-18 22:45 UTC by pixelflinger

what's not allowed at this point is an object which has both screen
space refraction and reflection.

this is accomplished by just always disabling screen-space reflections
for the translucent step of the refraction pass
![Screen Shot 2022-01-18 at 2 44 41 PM](https://user-images.githubusercontent.com/1240896/150030776-bba19770-fb9b-44f5-b8e5-084e97e49dc3.png)
.

2022-01-18 23:09 UTC, prideout approved these changes

2022-01-18 23:44 UTC, bejado approved these changes
So easy!

2022-01-19 00:37 UTC, romainguy approved these changes

2022-01-19 19:16 UTC, bejado requested changes
Can you update [this comment](https://github.com/google/filament/blob/4b572cf0657ce49b7e5aafd8420072655f6e71e7/libs/filamat/src/shaders/ShaderGenerator.cpp#L311-L314) in ShaderGenerator.cpp? Other than that, LGTM!

2022-01-19 19:16 UTC, bejado commented on filament/src/Renderer.cpp
> +                view.prepareSSR(ssrHandle,config.refractionLodOffset,
```suggestion
                view.prepareSSR(ssrHandle, config.refractionLodOffset,
```

2022-01-19 19:16 UTC, bejado commented on filament/src/Renderer.cpp
>                  // set screen-space reflections or screen-space refractions
```suggestion
                // set screen-space reflections and screen-space refractions
```

2022-01-19 21:30 UTC, merged