Change morphing APIs to support LOD
google/filament pull request #5080
Opened 2022-01-21 09:03 UTC by daemyung

@pixelflinger I have changed morphing APIs based on your comments. Please review my code. Thanks.

2022-01-21 17:52 UTC, pixelflinger approved these changes
Sounds good.

2022-01-21 17:55 UTC, romainguy reviewed
The Java/JS APIs need to be updated as well

2022-01-22 00:44 UTC, daemyung commented
@romainguy Please review Java and Web bindings. Actually I don't know JS, please let me know what should I do more if there are something to do.

2022-01-24 04:02 UTC, pixelflinger commented
> @romainguy Please review Java and Web bindings. Actually I don't know JS, please let me know what should I do more if there are something to do.

I don't know js either... I just wing it :-)

2022-01-24 16:50 UTC, prideout requested changes
This JS binding will not work because there is no class binding for MorphTargetBuffer.  In fact the `setMorphWeights` method that was recently added won't work either (JS does not have `float*` so it should actually take emscripten::val or std::vector.)

I think it's better to omit bindings than to create bindings that won't work.  In this PR, maybe we could just remove `setMorphWeights` and create an issue to do this work later.

2022-01-24 17:58 UTC, pixelflinger commented
looks like this need to be rebased/merged in top of #5079 ?

2022-01-24 23:40 UTC, daemyung commented
> This JS binding will not work because there is no class binding for MorphTargetBuffer. In fact the `setMorphWeights` method that was recently added won't work either (JS does not have `float*` so it should actually take emscripten::val or std::vector.)

Thanks! I have updated it.

> I think it's better to omit bindings than to create bindings that won't work. In this PR, maybe we could just remove `setMorphWeights` and create an issue to do this work later.

Thanks for your advice. I remove this binding.

2022-01-24 23:42 UTC, daemyung commented
> looks like this need to be rebased/merged in top of #5079 ?

I don't think so... is there any relations between two PRs?

2022-01-25 02:12 UTC, prideout approved these changes

2022-01-25 17:15 UTC, pixelflinger commented
> > looks like this need to be rebased/merged in top of #5079 ?
> 
> I don't think so... is there any relations between two PRs?

Well, in this PR `MorphTargetBuffer.cpp ` is entirely new.

2022-01-25 18:04 UTC, daemyung commented
> Well, in this PR `MorphTargetBuffer.cpp ` is entirely new.

@pixelflinger Yes because this is first time adding `MorphTargetBuffer``s Java binding.

2022-01-25 19:27 UTC, bejado approved these changes

2022-01-25 20:20 UTC, pixelflinger approved these changes

2022-01-26 01:14 UTC, daemyung commented on android/filament-android/src/main/java/com/google/android/filament/MorphTargetBuffer.java
> +                               @IntRange(from = 0) int targetIndex,
Thanks. It's fixed.

2022-01-26 05:57 UTC, merged