Create a dummpy MorphTargetBuffer if skinning is enabled
google/filament pull request #5104
Opened 2022-01-25 02:20 UTC by daemyung

Fixes #5085

2022-01-25 02:27 UTC, daemyung commented
Nice to see you a fox again!
<img width="229" alt="스크린샷 2022-01-25 오전 11 27 14" src="https://user-images.githubusercontent.com/7459074/150899507-f2d336ff-0549-4dc9-bb14-e48f543b521b.png">

2022-01-25 17:11 UTC, pixelflinger requested changes
@daemyung sorry this is not the right approach. This logic should reside in filament, not in gltfio.

I will take a look at fixing this today. 

Thank you again!

2022-01-25 17:11 UTC, pixelflinger commented on libs/gltfio/src/MorphHelper.cpp
> +                addPrimitive(mesh, pi, skin->joints_count, pair.second);
```suggestion
                addPrimitive(mesh, pi, (bool)skin->joints_count, pair.second);
```

2022-01-25 17:12 UTC, pixelflinger commented
I'm closing this PR because it is not the right approach, this logic should not be in `gltfio`.

2022-01-25 17:12 UTC, closed without merging

2022-01-26 02:34 UTC, daemyung commented
@pixelflinger Yes it's just W/A. I don't know where is the best place to create dummy resource.