Make sure one use the right combination of version
google/filament pull request #5174
Opened 2022-02-08 12:45 UTC by eliemichel

To avoid `Material version mismatch`

2022-02-08 18:23 UTC, pixelflinger approved these changes

2022-02-08 18:56 UTC, prideout requested changes
Ah thanks, yes it's hard to find bandwidth to always update the tutorials, this can prevent some frustration.

Maybe you could also update the HTML in `/docs/webgl/tutorial_redball.html`?

2022-02-09 10:15 UTC, eliemichel commented
idk, I was just reporting a small change on the fly but if need to clone the project + install build script dependencies and generate the html it becomes a bit painful, my bet is that it'll be much quicker if you do it. ;)

2022-02-09 17:42 UTC, prideout commented
I assumed you would manually modify the HTML since the change is so small.  But yes, either of us could do it.

2022-02-14 18:55 UTC, merged