Remove deprecated Stream APIs
google/filament pull request #5397
Opened 2022-04-05 19:19 UTC by pixelflinger

2022-04-05 20:11 UTC, bejado requested changes

2022-04-05 20:11 UTC, bejado commented on RELEASE_NOTES.md
> +- remove deprecated `Stream` APIs [⚠️ **API Change**].
Please rebase on main. This should go under v1.21.2.

2022-04-05 20:12 UTC, kpeeters commented
This means that you now require API 26, right? Any way you might reconsider this decision? It removes quite a large chunk of devices still out there.

2022-04-05 21:16 UTC, prideout reviewed
We need to update `StreamHelper.kt` and make sure that `sample-stream-test` still builds and runs.

2022-04-05 23:26 UTC, pixelflinger commented
> We need to update `StreamHelper.kt` and make sure that `sample-stream-test` still builds and runs.

How come everything built?

2022-04-05 23:27 UTC, pixelflinger commented
> This means that you now require API 26, right? Any way you might reconsider this decision? It removes quite a large chunk of devices still out there.

Sorry why is that? I think the solution that uses `import()` works everywhere.

2022-04-06 01:34 UTC, bejado approved these changes

2022-04-06 01:44 UTC, prideout approved these changes

2022-04-06 03:37 UTC, pixelflinger commented
converted to draft until we're ready to submit.

2022-04-13 21:04 UTC, bejado commented
Please rebase on main and update the release notes for 1.21.3

2022-04-14 19:51 UTC, merged