Always use homogeneous attachment sizes
google/filament pull request #5679
Opened 2022-06-10 20:43 UTC by bejado

Homogeneous attachments are a requirement for Metal (and possibly Vulkan) correctness. If rendering to a RenderTarget that has a smaller height than the underlying Texture, the Metal backend must set the Viewport to be the bottom-left of the texture, to match OGL. However, it can only do this correctly if all attachments have the same size.

2022-06-10 21:01 UTC, bejado commented
This causes an [assertion](https://github.com/google/filament/blob/9508bf2a0c996b47785fbc244a530e5287a37c80/filament/src/PostProcessManager.cpp#L1476) to fire when DOF is turned on:

```
// compute numbers of "safe" levels (should be 4, but can be 3 at half res)
const uint8_t mipmapCount = std::min(maxMipLevels, ctz(width | height));
assert_invariant(mipmapCount == maxMipLevels || mipmapCount == maxMipLevels-1);
```

2022-06-10 21:04 UTC, pixelflinger requested changes
I think we should add/update the asserts in the backends and in the framefraph.

2022-06-13 04:35 UTC, pixelflinger requested changes

2022-06-13 04:35 UTC, pixelflinger commented on filament/backend/src/metal/MetalHandles.mm
> +
this min/max method is good, but I think we can do better, you can check that the bitwise OR and the bitwise AND of all the values are the same. You can use the fact that:
if a==b, then (a&b) == (a|b) and by extension
if a==b and b==c, then (a&b&c) == (a|b|c)

2022-06-14 00:27 UTC, pixelflinger approved these changes

2022-06-14 16:03 UTC, prideout approved these changes

2022-06-14 17:05 UTC, merged