Get the morph target buffer
google/filament pull request #6107
Opened 2022-09-27 05:55 UTC by daemyung

2022-09-27 17:35 UTC, pixelflinger approved these changes

2022-09-28 18:23 UTC, prideout requested changes
The doc comment should also say: "or null if it doesn't exist".

Also I think the method can be marked `noexcept`.

2022-09-29 01:33 UTC, daemyung commented
@prideout Yes it's done.

2022-09-29 17:20 UTC, prideout approved these changes

2022-09-29 20:01 UTC, merged