Metal: generate argument buffer structures ourselves
google/filament pull request #6242
Opened 2022-10-28 18:52 UTC by bejado

We're using argument buffers for texture resources, however, we cannot rely on spirv-cross to generate the argument buffer definitions.

Consider a shader with 3 textures:
```
layout (set = 0, binding = 0) uniform sampler2D texture1;
layout (set = 0, binding = 1) uniform sampler2D texture2;
layout (set = 0, binding = 2) uniform sampler2D texture3;
```

If only texture1 and texture2 are used in the material, then texture3 will be optimized away.
This results in an argument buffer like the following:
```
struct spvDescriptorSetBuffer0 {
    texture2d<float> texture1 [[id(0)]];
    sampler texture1Smplr [[id(1)]];
    texture2d<float> texture2 [[id(2)]];
    sampler texture2Smplr [[id(3)]];
};
```

Note that this happens even if the "pad_argument_buffer_resources" and "force_active_argument_buffer_resources" options are true, because the optimization has already happened by the time the SPIR-V gets to spirv-cross.

This would be fine, except older Apple devices don't like it when the argument buffer in the shader doesn't precisely match the one generated at runtime.

So, this PR adds a`MetalArgumentBuffer ` class to replace spirv-cross' argument buffer definitions with our own that contain all the textures/samples, even those that would be optimized away.

2022-10-28 19:03 UTC, pixelflinger requested changes

2022-10-28 19:03 UTC, pixelflinger commented on libs/filamat/src/MetalArgumentBuffer.cpp
> +} // namespace filamat
no newline at end of file

2022-10-28 19:03 UTC, pixelflinger commented on libs/filamat/src/MetalArgumentBuffer.h
> +   public:
don't indent public/protected/private

2022-10-28 19:03 UTC, pixelflinger commented on libs/filamat/src/MetalArgumentBuffer.h
> +       public:
don't indent

2022-10-28 19:03 UTC, pixelflinger commented on libs/filamat/src/MetalArgumentBuffer.h
> +       private:
don't indent

2022-10-28 19:03 UTC, pixelflinger commented on libs/filamat/src/MetalArgumentBuffer.h
> +   private:
don't indent

2022-10-31 15:40 UTC, bejado commented on libs/filamat/src/GLSLPostProcessor.cpp
> +        delete argBuffer;
Good idea

2022-11-01 16:35 UTC, pixelflinger approved these changes

2022-11-01 16:44 UTC, merged