get rid of filamat-lite, which was poorly maintained
google/filament pull request #7211
Opened 2023-09-26 20:45 UTC by pixelflinger

2023-09-26 20:49 UTC, romainguy commented
You'll need to update README.md as well as it mentions it.

2023-09-26 21:01 UTC, romainguy requested changes

2023-09-27 18:30 UTC, bejado approved these changes

2023-09-28 23:10 UTC, pixelflinger commented on android/filamat-android/build.gradle
> -
done

2023-09-28 23:10 UTC, pixelflinger commented on android/samples/sample-material-builder/build.gradle
> -    // but comes with certain restrictions. See "Filamat Lite" in libs/filamat/README.md.
done

2023-09-28 23:10 UTC, pixelflinger commented on android/filamat-android/build.gradle
>          singleVariant("fullRelease") {
done

2023-09-28 23:25 UTC, romainguy approved these changes

2023-10-02 21:18 UTC, merged