Support stencil buffer when post-processing is disabled
google/filament pull request #7227
Opened 2023-10-04 03:54 UTC by bejado

Still need to add support for other backends' SwapChain implementations.

- [ ] OpenGL support
- [ ] Vulkan support

2023-10-04 17:25 UTC, pixelflinger requested changes
Please file an issue to implement support for gl and vk.

2023-10-04 17:25 UTC, pixelflinger commented on filament/src/details/Renderer.cpp
> +    if (outputIsSwapChain && view.isStencilBufferEnabled()) {
```suggestion
    if (UTILS_UNLIKELY(outputIsSwapChain && view.isStencilBufferEnabled())) {
```

2023-10-04 17:25 UTC, pixelflinger commented on filament/src/details/Renderer.cpp
> +                "CONFIG::CONFIG_HAS_STENCIL_BUFFER flag set.");
```suggestion
                "SwapChain::CONFIG_HAS_STENCIL_BUFFER flag set.");
```

2023-10-04 17:25 UTC, pixelflinger commented on NEW_RELEASE_NOTES.md
> +engine: Add support for stencil buffer when post-processing is disabled.
```suggestion
engine: Add support for stencil buffer when post-processing is disabled (Metal backend only).
```

2023-10-12 18:16 UTC, poweifeng approved these changes

2023-10-13 17:04 UTC, merged