fix install android debug samples apk error.
google/filament pull request #7230
Opened 2023-10-04 15:51 UTC by suzp1984

# cp not exist debug sample apk.

`./build.sh -p android -k sample-gltf-viewer -i debug`
Take `sample-gltf-viewer` as an example, above cmd will result in :

`cp: samples/sample-gltf-viewer/build/outputs/apk/debug/sample-gltf-viewer-debug-unsigned.apk: No such file or directory`

The root cause is that the `android` will signed the `debug` apk with `~/.android/debug.keystore`, which is the default generated by android gradle plugin globally.

2023-10-04 16:48 UTC, romainguy requested changes

2023-10-04 16:48 UTC, romainguy commented on build.sh
> +                    echo "Installing out/${sample}-release-unsigned.apk"
Don't rename please

2023-10-04 16:48 UTC, romainguy commented on build.sh
> +                        ../out/${sample}-release-unsigned.apk
Don't rename please

2023-10-05 00:48 UTC, suzp1984 commented on build.sh
> +                    echo "Installing out/${sample}-release-unsigned.apk"
done

2023-10-05 00:48 UTC, suzp1984 commented on build.sh
> +                        ../out/${sample}-release-unsigned.apk
done

2023-10-26 20:15 UTC, pixelflinger approved these changes

2024-03-23 05:58 UTC, suzp1984 commented
I notice this problem still exist.
`cp: samples/sample-gltf-viewer/build/outputs/apk/debug/sample-gltf-viewer-debug-unsigned.apk: No such file or directory`

2024-03-23 06:05 UTC, romainguy approved these changes

2024-03-23 06:05 UTC, merged