Fix some ES2 issues
google/filament pull request #7359
Opened 2023-11-13 23:09 UTC by elizagamedev

Fix specification of mipmaps when generating textures.

Fix oversight where emulated UBOs would not replace uniforms when swapped out for another.

2023-11-13 23:10 UTC, bejado approved these changes

2023-11-13 23:25 UTC, pixelflinger requested changes

2023-11-13 23:25 UTC, pixelflinger commented on filament/backend/src/opengl/OpenGLDriver.cpp
> +                                GLsizei(width >> level), GLsizei(height >> level), 0,
you need to `max(1, x)` here so that the width or height can't end-up being 0

2023-11-13 23:25 UTC, pixelflinger commented on filament/backend/src/opengl/OpenGLDriver.h
> +    GLuint lastAssignedEmulatedUboId = 0;
`m` prefix: `mLastAssignedEmulatedUboId`

2023-11-13 23:25 UTC, pixelflinger commented on filament/backend/src/opengl/OpenGLDriver.h
> +            GLuint id;
That's very unfortunate, it'll double the size of this structure for the regular case. I can't think of a better way though.

2023-11-14 00:38 UTC, pixelflinger approved these changes

2023-11-14 21:06 UTC, elizagamedev commented
I made a slight change. I added a fix to depth_main.fs to remove the ESSL 3.0+ specific syntax with ESSL 1.0 compatible syntax which was in #7358 . That PR depends on upstream changes so I agreed with @poweifeng to delay it for now, but this fix is still critical for FL0 to function.

2023-11-14 21:39 UTC, merged