Deprecate use of hat-trie
google/filament pull request #7889
Opened 2024-05-29 21:16 UTC by bejado

2024-05-29 21:21 UTC, poweifeng approved these changes

2024-05-29 23:25 UTC, pixelflinger approved these changes

2024-05-29 23:26 UTC, pixelflinger requested changes
The comment needs the bug number `FIXES=[]`

2024-05-30 22:26 UTC, pixelflinger approved these changes

2024-05-30 22:45 UTC, merged