Add ability to disable panning in the OrbitManipulator
google/filament pull request #7928
Opened 2024-06-15 12:23 UTC by mentholyspirit

It's useful when you want to have the ability to rotate the camera, but want to limit panning.

2024-06-17 17:47 UTC, poweifeng approved these changes

2024-06-17 17:47 UTC, poweifeng commented on libs/camutils/include/camutils/Manipulator.h
> +        Builder& panDisabled(bool enabled);  //! Sets whether panning with two fingers is enabled
I'd remove the "two fingers" part, which only applies to mobile.

2024-06-18 04:37 UTC, pixelflinger requested changes
rename `panDisabled`  to `panning(bool) where `true` means panning enabled and `false` means panning disabled. Make the default be `true`.

2024-06-18 04:37 UTC, pixelflinger commented on libs/camutils/include/camutils/Manipulator.h
> +        Builder& panDisabled(bool enabled);  //! Sets whether panning is enabled
rename to `panning`

2024-06-18 04:37 UTC, pixelflinger commented on android/filament-utils-android/src/main/java/com/google/android/filament/utils/Manipulator.java
> +        public Builder panDisabled(Boolean enabled) {
rename to `panning`

2024-06-18 04:37 UTC, pixelflinger commented on libs/camutils/include/camutils/Manipulator.h
> +        bool panDisabled;
rename to `panning`

2024-06-18 04:37 UTC, pixelflinger commented on libs/camutils/src/Manipulator.cpp
> +    details.panDisabled = enabled;
this is *very* confusing. It should all be done in terms of "panning being enabled or not".

2024-06-18 12:30 UTC, mentholyspirit commented
@pixelflinger The problem then comes when someone tries to use it like this:
`Config config = {};
config.upVector = vec2(1.f, 0.f);
mainpulator.setProperties(config)`
Then `panning` will be set to false, which is not the expected behaviour.

2024-06-18 22:00 UTC, pixelflinger commented
> @pixelflinger The problem then comes when someone tries to use it like this: `Config config = {}; config.upVector = vec2(1.f, 0.f); mainpulator.setProperties(config)` Then `panning` will be set to false, which is not the expected behaviour.

Why can't we set `panning` to `true` by default in `Config`?

2024-06-20 17:26 UTC, pixelflinger approved these changes

2024-06-21 17:39 UTC, pixelflinger commented
@mentholyspirit the Android presubmit is failing.

2024-06-27 00:05 UTC, merged