Update createTextureView API to include swizzling, implement on Metal
google/filament pull request #8077
Opened 2024-08-22 20:36 UTC by bejado

2024-08-23 18:01 UTC, pixelflinger requested changes
I like this!

2024-08-23 18:31 UTC, bejado commented on filament/backend/test/test_FeedbackLoops.cpp
> +                        backend::TextureSwizzle::CHANNEL_2, backend::TextureSwizzle::CHANNEL_3);
Yeah I was thinking about that. `createTextureViewSwizzle` would certainly be more ergonomic to use. Let me update it

2024-08-27 23:53 UTC, pixelflinger approved these changes
Looks good to me. Do you intend to implement the vk/gl sides, or should we do it?

2024-08-28 16:54 UTC, bejado commented
> Looks good to me. Do you intend to implement the vk/gl sides, or should we do it?

If you can do the GL side that would be great. I started to look into it but I got confused.

@poweifeng do you have bandwidth to implement the VK side? If not I'm happy to try to implement it myself.

2024-08-28 17:17 UTC, poweifeng commented
> > Looks good to me. Do you intend to implement the vk/gl sides, or should we do it?
> 
> If you can do the GL side that would be great. I started to look into it but I got confused.
> 
> @poweifeng do you have bandwidth to implement the VK side? If not I'm happy to try to implement it myself.

Sure, I can give it a try later this week.

2024-08-28 18:52 UTC, merged