vk: workaround a renderStandaloneView issue
google/filament pull request #8126
Opened 2024-09-13 17:41 UTC by poweifeng

Found through testing that renderStandaloneView+vk+swiftshader seems to cause synchronization issues, which results in incorrect rendering. Here we workaround the issue by forcibly flush and wait per renderStandaloneView call.

BUG=361822355

2024-09-13 17:46 UTC, z3moon approved these changes

2024-09-13 17:57 UTC, pixelflinger requested changes

2024-09-13 17:57 UTC, pixelflinger commented on filament/src/details/Renderer.cpp
> +            engine.flushAndWait();
I think that's too agressive. You should be able to just do a `driver.flush()` before the `renderInternal()` call.

2024-09-18 04:04 UTC, pixelflinger approved these changes

2024-09-18 05:47 UTC, merged